INSERT INTO CATEGORY (ID,NAME) VALUES (1,'Rock movies')
INSERT INTO CATEGORY (ID,NAME) VALUES (2,'Music movies')
INSERT INTO CATEGORY (ID,NAME) VALUES (3,'Biographical movies')

INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (1,'The Doors',1)
INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (2,'Almost Famous',1)
INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (3,'Satisfaction',1)
INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (4,'Great Balls of Fire!',1)

INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (5,'Rocketman',2)
INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (6,'Hungarian Rhapsody: Queen Live',2)
INSERT INTO MOVIE (ID,NAME,CATEGORY_ID) VALUES (7,'Judy',2)